---

## link seqeunce calculation
## link count per switch
link_ct: 1
# offset: "{{ hostvars['dc-gw01'].seq }}"
# links_seq:
#     - "{{ (seq-offset|int)*link_ct + 0 }}"
#     # - "{{ (seq-offset|int)*link_ct + 1 }}"

xconn_v4:
  - 
    pointa: "edge1"
    pointb: "dc-gw01"
    # seq is based on edge/bleaf, not isp-gw!
    seq: 0
    net: "38.142.190.96/29"
    netmask: 29
  - 
    pointa: "edge2"
    pointb: "dc-gw02"
    # seq is based on edge/bleaf, not isp-gw!
    seq: 0
    net: "209.249.45.126/30"
    netmask: 30

xconn_v6: 
  - 
    pointa: "edge1"
    pointb: "dc-gw01"
    # seq is based on edge/bleaf, not isp-gw!
    seq: 0
    net: "2001:550:2:61::2c8:0/112"
    netmask: 112
  - 
    pointa: "edge2"
    pointb: "dc-gw02"
    # seq is based on edge/bleaf, not isp-gw!
    seq: 0
    net: "2001:438:fffe::35a8/126"
    netmask: 126
