---
- hosts: poc
  gather_facts: false
  collections:
  - arista.eos

  tasks:
  - name: Disable BGP
    vars:
      local_as: "{{ 65000+rack_no }}"
    arista.eos.eos_bgp_global:
      config:
        as_number: "{{ edge_bgp.local_as }}"
      state: purged
    tags:
    - bgp

  - name: Disable Routing Policy
    eos_config:
        src: route_pol_del.j2
    tags:
    - rpol

  - name: Delete Spine L3 Interface
    arista.eos.eos_l3_interfaces:
      config:
      # - name: "loopback 0"
      # - name: "loopback 1"
      - name: "Eth1"
      state: deleted
    # loop: "{{ ports.fabric }}"
    tags:
    - l3port

  - name: Recover Original Hostname
    arista.eos.eos_hostname:
      config:
        hostname: "{{ name_orig }}"
      state: merged
    tags:
      - hostname

  # - name: Switch reload
  #   arista.eos.eos_command:
  #     commands:
  #     - command: reload power
  #       prompt: \[confirm\]
  #       answer: y
  #       newline: false
  #   tags:
  #     - reload

