ubuntu_users:
  - name: "netbox"
    groups: "devops"
    password: "{{ vault_netbox_password }}"
    state: "present"
  - name: "xji"
    groups: "devops"
    password: "{{ vault_xji_password }}"
    state: "present"

netbox_stable_version: 2.10.10
netbox_stable_uri: "https://github.com/netbox-community/netbox/archive/v{{ netbox_stable_version }}.tar.gz"

netbox_user: netbox
netbox_group: netbox
netbox_home: "/home/netbox"
netbox_releases_path: "{{ netbox_home }}/releases"
netbox_git_repo_path: "{{ netbox_releases_path }}/git-repo"
netbox_git_deploy_path: "{{ netbox_releases_path }}/git-deploy"
netbox_stable_path: "{{ netbox_releases_path }}/netbox-{{ netbox_stable_version }}"
netbox_current_path: "{{ netbox_home }}/current"
netbox_shared_path: "{{ netbox_home }}/shared"

netbox_superuser_enabled: true
netbox_superuser_username: netbox
netbox_superuser_password: "{{ vault_netbox_password }}"
netbox_superuser_email: netbox@localhost
netbox_superuser_create_token: false

netbox_database: netbox
netbox_database_user: netbox
netbox_database_password: "{{ vault_netbox_password }}"
netbox_database_host: localhost
netbox_database_port: 5432
#netbox_database_socket: /var/run/postgresql

netbox_database_conn_age: 300

netbox_database_maintenance: postgres

netbox_redis_host: 127.0.0.1
netbox_redis_port: 6379
netbox_redis_password: ''
netbox_redis_database: 0
netbox_redis_default_timeout: 300
netbox_redis_ssl_enabled: false
netbox_redis_insecure_skip_tls_verify: false

netbox_redis_cache_host: "{{ netbox_redis_host }}"
netbox_redis_cache_port: "{{ netbox_redis_port }}"
netbox_redis_cache_database: 1
netbox_redis_cache_password: "{{ netbox_redis_password }}"
netbox_redis_cache_default_timeout: "{{ netbox_redis_default_timeout }}"
netbox_redis_cache_ssl_enabled: "{{ netbox_redis_ssl_enabled }}"
netbox_redis_cache_insecure_skip_tls_verify: "{{ netbox_redis_insecure_skip_tls_verify }}"

netbox_config:
  #SECRET_KEY:
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
  #NAPALM_USERNAME:
  #NAPALM_PASSWORD:
  MEDIA_ROOT: "{{ netbox_shared_path }}/media"
  REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
  SCRIPTS_ROOT: "{{ netbox_shared_path }}/scripts"

redis_bind: 127.0.0.1
redis_version: 6.0.9
redis_checksum: sha256:labbdcf81c620e9f09cfd12e85d3bc631c897b2db7a55218fd8a65eaa37f86dd
