---
ansible_network_os: arista.eos.eos
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_connection: network_cli

ansible_ssh_user: admin
ansible_ssh_pass: "{{vault_ceos_password}}"
ansible_become: yes
ansible_become_method: sudo
ansible_become_pass: "{{ vault_ceos_password }}"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
